name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install node and build
      uses: actions/setup-node@v1
    - run: npm install
    - run: npm run build
    - name: Create file
      run: node ./createReadme.js
    - name: Commit and push if changed
      run: |
        git config --global user.email "usman.iunusov@gmail.com"
        git config --global user.name "usmanyunusov"
        git commit -am "Updated content"
        git push